### PR TITLE
Feature/69 create a bug report db table and model

### LINKED ISSUE #69: Create a Bug Report DB Table and Model
Create a ticket registration database table, with the following fields:

- Id
- CodeConnectId
- Ticket Name
- Date
- Affected Web Application
- Type (bug | Suggestion)
- Status Bug
- Involved Feature (Login, Challenges, Resources, Profile, etc)
- Description
- Priority
- Date Of Creation

### PR DESCRIPTION
**Pull request by FranHumbert**
Database Migrations: Added 4 migrations to create teams, team_user (pivot), tickets, and ticket_comments tables with all required fields and foreign key relationships.

Enums: Created 5 enums for type-safe handling:

TicketTypeEnum
TicketStatusEnum (open, in_progress, resolved, closed)
TicketPriorityEnum (low, medium, high, critical)
AffectedAppEnum
AffectedFunctionEnum
Team Model: Added Team model with user relationships through pivot table.

Ticket Model: Added Ticket model with relationships to users (reporter/assignee), teams, and comments. Uses enums for type-safe fields.

TicketComment Model: Added TicketComment model for ticket discussions, linked to tickets and users.

User Model Relations: Extended the User model with relationships for teams, tickets, and comments.

Factories: Created factories for Team, Ticket, and TicketComment to support testing and seeding.

Feature Tests: Added 11 feature tests covering ticket creation, updates, comments, and status changes. All tests passing.

### CODE REVIEW

**Review by rafacode86 — APPROVED** [review]
Creacion de tablas: 
- Tabla_team_user (pivot)
- Tabla_ teams
- Tabla_ticket_comments
- Tabla_tikets
Creación de Modelos
Creacion de enums para consumir en los formularios
Creacion de factories.

File: backend/src/app/Enums/AffectedAppEnum.php [hunk 1]
```diff
@@ -0,0 +1,18 @@
+<?php
+
+declare(strict_types=1);
+
+namespace App\Enums;
+
+enum AffectedAppEnum: string
+{
+    case WikiFrontend = 'wiki_frontend';
```
Comment (Saikurukaizen) [inline backend/src/app/Enums/AffectedAppEnum.php:9]: No entiendo los case aquí, por qué es necesario?

File: backend/src/app/Models/Team.php [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+declare(strict_types=1);
+
+namespace App\Models;
+
+use Illuminate\Database\Eloquent\Factories\HasFactory;
+use Illuminate\Database\Eloquent\Model;
+use Illuminate\Database\Eloquent\Relations\BelongsToMany;
+use Illuminate\Database\Eloquent\Relations\HasMany;
+
+class Team extends Model
```
Comment (Saikurukaizen) [inline backend/src/app/Models/Team.php]: Que quieres decir con Team? No hay necesidad

**Review by Saikurukaizen — COMMENTED** [review]
Tengo dudas al respecto:

Entiendo que haya Ticket, y hasta Comments pero...Teams?

No creo que sea necesaria las tablas teams. Al fin y al cabo, lo que importa es almacenar Tickets.

Entiendo que comments_table es para asignar quién lo crea y tal. Pero creo que hay trabajo de más

**Review by albertvallsbe — APPROVED** [review]

**Review by kenan-it-academy — CHANGES_REQUESTED** [review]
Pero a ver, los comments no entran en la historia, no?

**Comment by FranHumbert** [comment]
@kenan-it-academy 
image
Los coments si que lo pedian

**Review by kenan-it-academy — APPROVED** [review]
