### PR TITLE
fix: add project form validation rules and update tests

### LINKED ISSUE #328: Add and improve validation rules for the project creation form
****Objective****

add and improve validation rules for the project creation form:

✘  Make `description` required
✘  Make `dev_front_number` and `dev_back_number` required (min 1)
✘  Ensure `limit_date_inscription` is today or a future date
✘  Add `Other` option to `LanguageEnum`
✘  Update tests and swagger doc

### PR DESCRIPTION
**Pull request by VictorCharneco**
****OBJECTIVE****

add and improve validation rules for the project creation form:

✘ Make `description` required
✘ Make `dev_front_number` and `dev_back_number` required (min 1)
✘ Ensure `limit_date_inscription` is today or a future date
✘ Add `Other` option to `LanguageEnum`
✘ Update tests and swagger doc

### CODE REVIEW

**Review by H3llynx — APPROVED** [review]

**Review by AlexBeltran31 — APPROVED** [review]
Everything OK

File: backend/src/database/factories/TechnicalTestFactory.php [hunk 1]
```diff
@@ -12,7 +12,7 @@ public function definition(): array
     {
         return [
             'title' => $this->faker->sentence(4),
-            'language' => $this->faker->randomElement(LanguageEnum::values()),
+            'language' => $this->faker->randomElement(['PHP', 'JavaScript', 'React', 'TypeScript', 'Python', 'Java']),
```
Comment (kenan-it-academy) [inline backend/src/database/factories/TechnicalTestFactory.php]: wait why this change? This change seems bad. Introducing magic strings

File: backend/src/tests/Feature/ListProjects/ListProjectsStoreTest.php [hunk 2]
```diff
@@ -355,4 +373,56 @@ public function test_dev_back_number_must_be_at_least_1():void{
 
         $response->assertStatus(422);
     }
+
+    public function test_description_is_required():void{
```
Comment (kenan-it-academy) [inline backend/src/tests/Feature/ListProjects/ListProjectsStoreTest.php:282]: Extract common parts of all these tests, WAY too much duplication. Also add backlog task to split this file, it's HUGE.

**Review by kenan-it-academy — CHANGES_REQUESTED** [review]

**Comment by VictorCharneco** [comment]
i've extracted `validProjectPayload()` helper to reduce duplication at all tests, and fixed magic strings in `TechnicalTestFactory` by using array_filter at the enum
will create a backlog issue to split the file

File: backend/src/database/factories/TechnicalTestFactory.php [hunk 3]
```diff
@@ -12,7 +12,9 @@ public function definition(): array
     {
         return [
             'title' => $this->faker->sentence(4),
-            'language' => $this->faker->randomElement(LanguageEnum::values()),
+            'language' => $this->faker->randomElement(
+                array_values(array_filter(LanguageEnum::values(), fn($value) => $value !== LanguageEnum::Other->value))
```
Comment (kenan-it-academy) [inline backend/src/database/factories/TechnicalTestFactory.php]: I still don't understand. Why can't we allow the value to be Other? It's a valid option, right? 😕

Comment (VictorCharneco) [reply backend/src/database/factories/TechnicalTestFactory.php]: now i think i got it, Kenan, should I add a migration to include Other in the technical_tests enum?

File: backend/src/app/Enums/LanguageEnum.php [hunk 4]
```diff
@@ -13,6 +13,7 @@ enum LanguageEnum: string
     case TypeScript = 'TypeScript';
     case Python = 'Python';
     case SQL = 'SQL';
+    case Other = 'Other';
```
Comment (kenan-it-academy) [inline backend/src/app/Enums/LanguageEnum.php:16]: @VictorCharneco so you're saying this Enum value is added here but not in the Database? I still don't understand 😅 

ELI5 pls 🤣

**Review by kenan-it-academy — APPROVED** [review]
